name: Containerized Train CI/CD
run-name: Train CI/CD
on: [push]
jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker build -t "mbouzayeni/train-schedule:$GITHUB_SHA" .
      - name: Save the image to a tar file
        run: docker save mbouzayeni/train-schedule:$GITHUB_SHA > train-schedule.tar.gz
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: train-schedule.tar.gz
          path: ./train-schedule.tar.gz
  PushDockerImage:
    runs-on: ubuntu-latest
    needs: BuildDockerImage
    steps:
      - name: Downlaod artifact
        uses: actions/download-artifact@v2
        with:
          name: train-schedule.tar.gz
      - name: Load Docker Image
        run: docker load --input train-schedule.tar.gz
      - name: Login to docker hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: docker push mbouzayeni/train-schedule:$GITHUB_SHA            
  # DeployToProduction:
  #   runs-on: ubuntu-latest
  #   needs: PushDockerImage
  #   steps:
  #     - name: Login to docker hub
  #       run: docker login https://registry.hub.docker.com --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
  #     - name: 
  #     - name: Pull the image
  #       run: docker pull mbouzayeni/train-schedule:$GITHUB_SHA
  #     - name:     